#!/usr/bin/env python3
"""Rebuild signup/ROSTER.md from the signup/lectureNN-*.md files.

Each sign-up file carries a small YAML-ish front matter block:

    ---
    name: Tong Li
    student_id: 20261201094
    email: litong@westlake.edu.cn
    github: tongli
    lecture: 9
    teammates: Name A, Name B
    ---

Stdlib only. Run from the repository root: python3 tools/build_roster.py
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SIGNUP = ROOT / "signup"

LECTURES = {
    3: ("2026-09-08", "Reaction networks, with the central dogma as the worked example"),
    4: ("2026-09-10", "Dynamics: local stability, phase portraits, bifurcations"),
    5: ("2026-09-15", "Stochastic dynamics: the master equation and Gillespie"),
    6: ("2026-09-17", "Timescale separation: singular perturbation, QSSA, telegraph model"),
    7: ("2026-09-22", "Equilibrium parts driven out of equilibrium"),
    8: ("2026-09-24", "The cell as a biomachine: binding and catalysis"),
    9: ("2026-09-29", "Multistability and oscillations"),
    10: ("2026-10-08", "The adaptation biomachine"),
    11: ("2026-10-13", "Analysis of binding and catalysis via reaction-order structure"),
    12: ("2026-10-15", "The computation biomachine"),
    13: ("2026-10-20", "The metabolic biomachine"),
    14: ("2026-10-22", "The growth biomachine"),
    15: ("2026-10-27", "Introduction to protein design"),
    16: ("2026-10-29", "Foundational virtual cells that are fully mechanistic"),
}
CAP = 3
FLOOR = 2


def parse(path):
    text = path.read_text(encoding="utf-8")
    m = re.match(r"\s*---\s*\n(.*?)\n---\s*\n?", text, re.S)
    if not m:
        return None
    out = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            out[k.strip().lower()] = v.strip()
    return out


def main():
    entries = []
    bad = []
    for p in sorted(SIGNUP.glob("lecture*.md")):
        if p.name == "TEMPLATE.md":
            continue
        d = parse(p)
        if not d:
            bad.append((p.name, "no front matter block"))
            continue
        try:
            n = int(str(d.get("lecture", "")).strip())
        except ValueError:
            bad.append((p.name, "lecture is not a number"))
            continue
        if n not in LECTURES:
            bad.append((p.name, f"lecture {n} is not a student-taught lecture (3-16)"))
            continue
        name = d.get("name") or p.stem.split("-", 1)[-1]
        if d.get("name_zh"):
            name = f"{name} ({d['name_zh']})"
        entries.append((n, name, d.get("github", ""), p.name))

    by_lecture = {n: [] for n in LECTURES}
    for n, name, gh, fn in sorted(entries):
        by_lecture[n].append((name, gh, fn))

    lines = [
        "# Teaching roster",
        "",
        "*Rebuilt automatically on every merge to `main` by `.github/workflows/roster.yml`.*",
        "*Do not edit this file by hand; edit your own `signup/lectureNN-yourname.md` instead.*",
        "",
        f"**{len(entries)} of 35 students signed up.** Each lecture takes at most {CAP} "
        f"and needs at least {FLOOR}.",
        "",
        "| # | Date | Topic | Team | Room left |",
        "|---|---|---|---|---|",
    ]
    for n, (date, topic) in LECTURES.items():
        team = by_lecture[n]
        who = ", ".join(f"{name}" + (f" (@{gh})" if gh else "") for name, gh, _ in team) or "_open_"
        left = CAP - len(team)
        if len(team) == 0:
            room = f"**{left} places, none yet**"
        elif len(team) < FLOOR:
            room = f"**{left}, needs {FLOOR - len(team)} more**"
        elif left > 0:
            room = f"{left}"
        else:
            room = "full"
        lines.append(f"| {n} | {date} | {topic} | {who} | {room} |")

    if bad:
        lines += ["", "## Files that could not be read", ""]
        lines += [f"- `signup/{fn}`: {why}" for fn, why in bad]

    lines += [
        "",
        "---",
        "",
        "To sign up: fork this repository, copy `signup/TEMPLATE.md` to "
        "`signup/lectureNN-yourname.md`, fill it in, and open a pull request. "
        "It merges automatically once the filename and contents check out.",
        "",
    ]
    (SIGNUP / "ROSTER.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"roster rebuilt: {len(entries)} sign-ups, {len(bad)} unreadable")
    return 0


if __name__ == "__main__":
    sys.exit(main())
